apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server-deployment
  labels:
    app: user-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-server
  template:
    metadata:
      labels:
        app: user-server
    spec:
      volumes:
        - name: songs-data
          persistentVolumeClaim: 
            claimName: songs-pvc
      containers:
      - name: user-server
        image: masteradios123/music-streaming-user-server
        envFrom:
          - configMapRef:
              name: user-server-config
        
        volumeMounts:                 
          - name: songs-data                
            mountPath: /app/sg         
        ports:
        - containerPort: 4003
