server:
  port:
    4001


spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${FRONT_END_URL}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: music-service
          uri: ${MUSIC_SERVICE_URL}
          predicates:
            - Path=/api/music/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
